default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  encoding: unicode
  min_messages: WARNING

development:
  <<: *default
  database: sonar_development

test:
  <<: *default
  database: sonar_test

production:
  <<: *default
  database: sonar_production
